name: "Publish container templates"
on:
  workflow_run:
    workflows: [Tests]
    types: [completed]
    branches: [main]

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Publish Templates"
        uses: devcontainers/action@v1
        with:
          publish-templates: "true"
          base-path-to-templates: "./src"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
