name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: "Run test suite for templates"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install devcontainer CLI
        run: npm install -g @devcontainers/cli

      # TODO: This'll do for now, but generalise these soon
      - name: Run Node.js template test
        run: test/nodejs/test.sh
      - name: Run Ruby template test
        run: test/ruby/test.sh
