name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: "Run test suite for templates"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Run linting
        run: test/lint.sh

      # TODO: This'll do for now, but generalise these soon
      - name: Run barebones-nodejs template test
        run: test/barebones-nodejs/test.sh
      - name: Run barebones-ruby template test
        run: test/barebones-ruby/test.sh
